name: personal_flutter_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  blur: ^4.0.0
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_rating_stars: ^1.1.0
  font_awesome_flutter: ^10.8.0
  google_nav_bar: ^5.0.7
  gradient_borders: ^1.0.1
  gradient_icon: ^2.0.9
  http: ^0.13.5
  page_view_dot_indicator: ^2.3.0
  pexels_api: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  # fonts:
  #   - asset: path